/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ParceriaRouteImport } from './routes/parceria'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IgrejasIndexRouteImport } from './routes/igrejas.index'
import { Route as IgrejasSlugRouteImport } from './routes/igrejas.$slug'
import { Route as AdminTrocarSenhaRouteImport } from './routes/admin.trocar-senha'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminUsuariosRouteImport } from './routes/_admin.admin.usuarios'
import { Route as AdminAdminSolicitacoesRouteImport } from './routes/_admin.admin.solicitacoes'
import { Route as AdminAdminPaginasRouteImport } from './routes/_admin.admin.paginas'
import { Route as AdminAdminNoticiasRouteImport } from './routes/_admin.admin.noticias'
import { Route as AdminAdminGaleriaRouteImport } from './routes/_admin.admin.galeria'
import { Route as AdminAdminCarrosselRouteImport } from './routes/_admin.admin.carrossel'
import { Route as AdminAdminIgrejasIndexRouteImport } from './routes/_admin.admin.igrejas.index'
import { Route as AdminAdminIgrejasNovoRouteImport } from './routes/_admin.admin.igrejas.novo'
import { Route as AdminAdminIgrejasIdRouteImport } from './routes/_admin.admin.igrejas.$id'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceriaRoute = ParceriaRouteImport.update({
  id: '/parceria',
  path: '/parceria',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IgrejasIndexRoute = IgrejasIndexRouteImport.update({
  id: '/igrejas/',
  path: '/igrejas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IgrejasSlugRoute = IgrejasSlugRouteImport.update({
  id: '/igrejas/$slug',
  path: '/igrejas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrocarSenhaRoute = AdminTrocarSenhaRouteImport.update({
  id: '/admin/trocar-senha',
  path: '/admin/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsuariosRoute = AdminAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSolicitacoesRoute = AdminAdminSolicitacoesRouteImport.update({
  id: '/admin/solicitacoes',
  path: '/admin/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPaginasRoute = AdminAdminPaginasRouteImport.update({
  id: '/admin/paginas',
  path: '/admin/paginas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNoticiasRoute = AdminAdminNoticiasRouteImport.update({
  id: '/admin/noticias',
  path: '/admin/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminGaleriaRoute = AdminAdminGaleriaRouteImport.update({
  id: '/admin/galeria',
  path: '/admin/galeria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCarrosselRoute = AdminAdminCarrosselRouteImport.update({
  id: '/admin/carrossel',
  path: '/admin/carrossel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIgrejasIndexRoute = AdminAdminIgrejasIndexRouteImport.update({
  id: '/admin/igrejas/',
  path: '/admin/igrejas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIgrejasNovoRoute = AdminAdminIgrejasNovoRouteImport.update({
  id: '/admin/igrejas/novo',
  path: '/admin/igrejas/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIgrejasIdRoute = AdminAdminIgrejasIdRouteImport.update({
  id: '/admin/igrejas/$id',
  path: '/admin/igrejas/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/parceria': typeof ParceriaRoute
  '/sobre': typeof SobreRoute
  '/tours': typeof ToursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trocar-senha': typeof AdminTrocarSenhaRoute
  '/igrejas/$slug': typeof IgrejasSlugRoute
  '/igrejas/': typeof IgrejasIndexRoute
  '/admin/carrossel': typeof AdminAdminCarrosselRoute
  '/admin/galeria': typeof AdminAdminGaleriaRoute
  '/admin/noticias': typeof AdminAdminNoticiasRoute
  '/admin/paginas': typeof AdminAdminPaginasRoute
  '/admin/solicitacoes': typeof AdminAdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/igrejas/$id': typeof AdminAdminIgrejasIdRoute
  '/admin/igrejas/novo': typeof AdminAdminIgrejasNovoRoute
  '/admin/igrejas/': typeof AdminAdminIgrejasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/parceria': typeof ParceriaRoute
  '/sobre': typeof SobreRoute
  '/tours': typeof ToursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trocar-senha': typeof AdminTrocarSenhaRoute
  '/igrejas/$slug': typeof IgrejasSlugRoute
  '/igrejas': typeof IgrejasIndexRoute
  '/admin/carrossel': typeof AdminAdminCarrosselRoute
  '/admin/galeria': typeof AdminAdminGaleriaRoute
  '/admin/noticias': typeof AdminAdminNoticiasRoute
  '/admin/paginas': typeof AdminAdminPaginasRoute
  '/admin/solicitacoes': typeof AdminAdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/igrejas/$id': typeof AdminAdminIgrejasIdRoute
  '/admin/igrejas/novo': typeof AdminAdminIgrejasNovoRoute
  '/admin/igrejas': typeof AdminAdminIgrejasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/parceria': typeof ParceriaRoute
  '/sobre': typeof SobreRoute
  '/tours': typeof ToursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/trocar-senha': typeof AdminTrocarSenhaRoute
  '/igrejas/$slug': typeof IgrejasSlugRoute
  '/igrejas/': typeof IgrejasIndexRoute
  '/_admin/admin/carrossel': typeof AdminAdminCarrosselRoute
  '/_admin/admin/galeria': typeof AdminAdminGaleriaRoute
  '/_admin/admin/noticias': typeof AdminAdminNoticiasRoute
  '/_admin/admin/paginas': typeof AdminAdminPaginasRoute
  '/_admin/admin/solicitacoes': typeof AdminAdminSolicitacoesRoute
  '/_admin/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/igrejas/$id': typeof AdminAdminIgrejasIdRoute
  '/_admin/admin/igrejas/novo': typeof AdminAdminIgrejasNovoRoute
  '/_admin/admin/igrejas/': typeof AdminAdminIgrejasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeria'
    | '/noticias'
    | '/parceria'
    | '/sobre'
    | '/tours'
    | '/admin/login'
    | '/admin/trocar-senha'
    | '/igrejas/$slug'
    | '/igrejas/'
    | '/admin/carrossel'
    | '/admin/galeria'
    | '/admin/noticias'
    | '/admin/paginas'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/igrejas/$id'
    | '/admin/igrejas/novo'
    | '/admin/igrejas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/noticias'
    | '/parceria'
    | '/sobre'
    | '/tours'
    | '/admin/login'
    | '/admin/trocar-senha'
    | '/igrejas/$slug'
    | '/igrejas'
    | '/admin/carrossel'
    | '/admin/galeria'
    | '/admin/noticias'
    | '/admin/paginas'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/igrejas/$id'
    | '/admin/igrejas/novo'
    | '/admin/igrejas'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/galeria'
    | '/noticias'
    | '/parceria'
    | '/sobre'
    | '/tours'
    | '/admin/login'
    | '/admin/trocar-senha'
    | '/igrejas/$slug'
    | '/igrejas/'
    | '/_admin/admin/carrossel'
    | '/_admin/admin/galeria'
    | '/_admin/admin/noticias'
    | '/_admin/admin/paginas'
    | '/_admin/admin/solicitacoes'
    | '/_admin/admin/usuarios'
    | '/_admin/admin/'
    | '/_admin/admin/igrejas/$id'
    | '/_admin/admin/igrejas/novo'
    | '/_admin/admin/igrejas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  NoticiasRoute: typeof NoticiasRoute
  ParceriaRoute: typeof ParceriaRoute
  SobreRoute: typeof SobreRoute
  ToursRoute: typeof ToursRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTrocarSenhaRoute: typeof AdminTrocarSenhaRoute
  IgrejasSlugRoute: typeof IgrejasSlugRoute
  IgrejasIndexRoute: typeof IgrejasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceria': {
      id: '/parceria'
      path: '/parceria'
      fullPath: '/parceria'
      preLoaderRoute: typeof ParceriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igrejas/': {
      id: '/igrejas/'
      path: '/igrejas'
      fullPath: '/igrejas/'
      preLoaderRoute: typeof IgrejasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igrejas/$slug': {
      id: '/igrejas/$slug'
      path: '/igrejas/$slug'
      fullPath: '/igrejas/$slug'
      preLoaderRoute: typeof IgrejasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trocar-senha': {
      id: '/admin/trocar-senha'
      path: '/admin/trocar-senha'
      fullPath: '/admin/trocar-senha'
      preLoaderRoute: typeof AdminTrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/usuarios': {
      id: '/_admin/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminAdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/solicitacoes': {
      id: '/_admin/admin/solicitacoes'
      path: '/admin/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminAdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/paginas': {
      id: '/_admin/admin/paginas'
      path: '/admin/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AdminAdminPaginasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/noticias': {
      id: '/_admin/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminAdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/galeria': {
      id: '/_admin/admin/galeria'
      path: '/admin/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AdminAdminGaleriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/carrossel': {
      id: '/_admin/admin/carrossel'
      path: '/admin/carrossel'
      fullPath: '/admin/carrossel'
      preLoaderRoute: typeof AdminAdminCarrosselRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/igrejas/': {
      id: '/_admin/admin/igrejas/'
      path: '/admin/igrejas'
      fullPath: '/admin/igrejas/'
      preLoaderRoute: typeof AdminAdminIgrejasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/igrejas/novo': {
      id: '/_admin/admin/igrejas/novo'
      path: '/admin/igrejas/novo'
      fullPath: '/admin/igrejas/novo'
      preLoaderRoute: typeof AdminAdminIgrejasNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/igrejas/$id': {
      id: '/_admin/admin/igrejas/$id'
      path: '/admin/igrejas/$id'
      fullPath: '/admin/igrejas/$id'
      preLoaderRoute: typeof AdminAdminIgrejasIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCarrosselRoute: typeof AdminAdminCarrosselRoute
  AdminAdminGaleriaRoute: typeof AdminAdminGaleriaRoute
  AdminAdminNoticiasRoute: typeof AdminAdminNoticiasRoute
  AdminAdminPaginasRoute: typeof AdminAdminPaginasRoute
  AdminAdminSolicitacoesRoute: typeof AdminAdminSolicitacoesRoute
  AdminAdminUsuariosRoute: typeof AdminAdminUsuariosRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminIgrejasIdRoute: typeof AdminAdminIgrejasIdRoute
  AdminAdminIgrejasNovoRoute: typeof AdminAdminIgrejasNovoRoute
  AdminAdminIgrejasIndexRoute: typeof AdminAdminIgrejasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCarrosselRoute: AdminAdminCarrosselRoute,
  AdminAdminGaleriaRoute: AdminAdminGaleriaRoute,
  AdminAdminNoticiasRoute: AdminAdminNoticiasRoute,
  AdminAdminPaginasRoute: AdminAdminPaginasRoute,
  AdminAdminSolicitacoesRoute: AdminAdminSolicitacoesRoute,
  AdminAdminUsuariosRoute: AdminAdminUsuariosRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminIgrejasIdRoute: AdminAdminIgrejasIdRoute,
  AdminAdminIgrejasNovoRoute: AdminAdminIgrejasNovoRoute,
  AdminAdminIgrejasIndexRoute: AdminAdminIgrejasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  NoticiasRoute: NoticiasRoute,
  ParceriaRoute: ParceriaRoute,
  SobreRoute: SobreRoute,
  ToursRoute: ToursRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTrocarSenhaRoute: AdminTrocarSenhaRoute,
  IgrejasSlugRoute: IgrejasSlugRoute,
  IgrejasIndexRoute: IgrejasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
